name: CodeSync VSCode Plugin Tests
run-name: ${{ github.actor }} is testing CodeSync VSCode Plugin 🚀
on: [push]
jobs:
  VSCode-Plugin-Tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "token => ${{ github.token }}, GITHUB_TOKEN => ${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.13.2'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile # optional, --immutable
      - run: yarn test
      - uses: zgosalvez/github-actions-report-lcov@v1.5.0
        with:
          coverage-files: coverage/lcov.info
          minimum-coverage: 80
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}